---

- name: Ensure the Apt Package is Updated
  apt:
    update_cache: yes
    
- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Start service Apache2, if not started
  service:
    name: apache2
    state: started
#   enable: True (???)
