---
- name: "Importing RedHat task list . . ."
  import_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'
- name: "Importing Debian task list . . ."
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
