---

#- name: Upgrade all yum packages.
#  yum:
#    name: "*"
#    state: latest

- name: Enable EPEL
  yum:
    name: epel-release
    state: present

- name: Install Apache
  yum:
    name: httpd
    state: latest

- name: Start service httpd, if not started
  service:
    name: httpd
    state: started
#   enable: True (???)
